language: go

sudo: false

os:
  - linux
  - osx 

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

script: 
 - go vet ./...
 - go test -v -cpu=2 ./...
 - go test -cpu=2 -short -race ./...
 - diff <(gofmt -d .) <("")

matrix:
  allow_failures:
    - go: 'master'
  fast_finish: true
